[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "0.11"
winit = "0.29"
softbuffer = "0.4"
cosmic-text = { version = "0.11.2", features = ["shape-run-cache"] }
once_cell = "1.19"
dirs = "5.0"
ignore = "0.4"
log = "0.4"
pretty_env_logger = "0.5"
crossbeam-channel = "0.5"
clap = { version = "4.5", features = ["derive"] }
open = "5.0"
walkdir = "2.5"
rayon = "1.9"

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1

[dev-dependencies]
divan = "0.1.14"

[[bench]]
name = "files"
harness = false
