[package]
name = "launchr"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30"
softbuffer = "0.4"
cosmic-text = { version = "0.13.2", features = ["shape-run-cache"] }
once_cell = "1.21"
dirs = "6.0"
ignore = "0.4"
log = "0.4"
pretty_env_logger = "0.5"
crossbeam-channel = "0.5"
clap = { version = "4.5", features = ["derive"] }
open = "5.3"
walkdir = "2.5"
rayon = "1.10"
nucleo-matcher = "0.3.1"
anyhow = "1.0.97"
bincode = "2.0.1"

[profile.release]
strip = "debuginfo"
lto = true

[profile.bench]
lto = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
image = "0.25.5"

[[bench]]
name = "files"
harness = false

[[bench]]
name = "desktop_files"
harness = false

[[bench]]
name = "text_render"
harness = false

