[package]
name = "launcher-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "0.11"
winit = "0.29"
softbuffer = "0.4"
cosmic-text = { version = "0.11.2", features = ["shape-run-cache"] }
once_cell = "1.19"
dirs = "5.0"
ignore = "0.4"

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1
